databaseProfile:
  database:
    host: "154.53.63.99"
    port: 5432
    username: ${file:/run/secrets/db_username}
    password: ${file:/run/secrets/db_password}
    database: "digital_learning"
    maxConn: 5
    maxIdle: 5
    lifeTime: 5
  timeout: 30000

listener:
  host: "0.0.0.0"
  port: 8001

auth:
  accessSecret: ${file:/run/secrets/auth_access_secret}
  accessExpiry: 184000
  refreshSecret: ${file:/run/secrets/auth_refresh_secret}

redis:
  host: "154.53.63.99"
  port: "6379"
  password: ${file:/run/secrets/redis_password}

jaeger:
  host: "154.53.63.99"
  port: "6831"
  tracePerSecond: 100
  serviceName: "face-recognition-svc"

minioProfile:
  host: "154.53.63.99"
  port: "7000"
  username: ${file:/run/secrets/minio_username}
  secretKey: ${file:/run/secrets/minio_secret_key}
  tls: false
  region: "id-jkt-1"
  bucket: "face-dataset"

api:
  processingsvc:
    host: "http://localhost"
    port: 8002
    endpoint: "/train-model"

rabbitmq:
  host: "154.53.63.99"
  port: "5672"
  username: ${file:/run/secrets/rabbitmq_username}
  password: ${file:/run/secrets/rabbitmq_password}
